create table if not exists catalog.content_block_competency (
  content_block_id bigint not null references catalog.content_block(id) on delete cascade,
  competency_id bigint not null references catalog.competency(id) on delete cascade,
  position integer not null default 1 check (position > 0),
  weight numeric(5,4) not null default 1.0000 check (weight > 0 and weight <= 1),
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (content_block_id, competency_id),
  unique (content_block_id, position)
);

create index if not exists idx_catalog_block_competency_competency
  on catalog.content_block_competency(competency_id, content_block_id);

create unique index if not exists idx_catalog_block_competency_primary
  on catalog.content_block_competency(content_block_id)
  where is_primary;

drop trigger if exists tr_catalog_block_competency_updated_at on catalog.content_block_competency;
create trigger tr_catalog_block_competency_updated_at
before update on catalog.content_block_competency
for each row execute procedure private.touch_updated_at();

grant select on catalog.content_block_competency to anon, authenticated;

alter table catalog.content_block_competency enable row level security;

drop policy if exists block_competency_public_select on catalog.content_block_competency;
create policy block_competency_public_select on catalog.content_block_competency
for select to anon, authenticated
using (
  exists (
    select 1
    from catalog.content_block as block
    join catalog.course as course
      on course.id = block.course_id
    join catalog.track as track
      on track.id = course.track_id
    where block.id = content_block_competency.content_block_id
      and course.status = 'published'
      and track.is_published
  )
);

with competency_counts as (
  select
    course_competency.course_id,
    count(*)::integer as competency_count
  from catalog.course_competency
  group by course_competency.course_id
),
competency_buckets as (
  select
    course_competency.course_id,
    course_competency.competency_id,
    row_number() over (
      partition by course_competency.course_id
      order by course_competency.position, course_competency.competency_id
    ) as competency_bucket
  from catalog.course_competency
),
block_buckets as (
  select
    block.id as content_block_id,
    block.course_id,
    ntile(competency_counts.competency_count) over (
      partition by block.course_id
      order by block.position, block.id
    ) as competency_bucket
  from catalog.content_block as block
  join competency_counts
    on competency_counts.course_id = block.course_id
)
insert into catalog.content_block_competency (
  content_block_id,
  competency_id,
  position,
  weight,
  is_primary
)
select
  block_buckets.content_block_id,
  competency_buckets.competency_id,
  1,
  1.0000,
  true
from block_buckets
join competency_buckets
  on competency_buckets.course_id = block_buckets.course_id
 and competency_buckets.competency_bucket = block_buckets.competency_bucket
on conflict (content_block_id, competency_id) do update
  set position = excluded.position,
      weight = excluded.weight,
      is_primary = excluded.is_primary,
      updated_at = now();

create table if not exists learning.spaced_schedule (
  id bigint generated by default as identity primary key,
  person_id uuid not null references identity.person(id) on delete cascade,
  competency_id bigint not null references catalog.competency(id) on delete cascade,
  source_content_block_id bigint references catalog.content_block(id) on delete set null,
  next_review_at timestamptz not null,
  stability numeric(8,2) not null default 0,
  difficulty numeric(4,2) not null default 0,
  last_reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (person_id, competency_id)
);

create index if not exists idx_learning_spaced_schedule_person_next
  on learning.spaced_schedule(person_id, next_review_at);

create index if not exists idx_learning_spaced_schedule_competency
  on learning.spaced_schedule(competency_id, person_id);

drop trigger if exists tr_learning_spaced_schedule_updated_at on learning.spaced_schedule;
create trigger tr_learning_spaced_schedule_updated_at
before update on learning.spaced_schedule
for each row execute procedure private.touch_updated_at();

grant select, insert, update on learning.spaced_schedule to authenticated;

alter table learning.spaced_schedule enable row level security;

drop policy if exists spaced_schedule_self_all on learning.spaced_schedule;
create policy spaced_schedule_self_all on learning.spaced_schedule
for all to authenticated
using ((select auth.uid()) = person_id)
with check ((select auth.uid()) = person_id);

drop view if exists public.platform_portal_snapshot_v;
drop view if exists learning.v_student_risk;
drop trigger if exists on_legacy_progress_changed_platform_v3 on public.progress;
drop function if exists private.sync_learning_attempt_from_legacy_progress();

create temporary table tmp_mastery_state_legacy on commit drop as
select
  mastery.person_id,
  mastery.content_block_id,
  mastery.repetitions,
  mastery.interval_days,
  mastery.ease_factor,
  mastery.last_reviewed_at,
  mastery.next_review_at,
  mastery.created_at,
  mastery.updated_at
from learning.mastery_state as mastery;

alter table learning.mastery_state
  drop constraint if exists mastery_state_pkey;

alter table learning.mastery_state
  drop constraint if exists mastery_state_content_block_id_fkey;

alter table learning.mastery_state
  add column if not exists competency_id bigint references catalog.competency(id) on delete cascade;

alter table learning.mastery_state
  add column if not exists level numeric(4,2) not null default 0.00
  check (level >= 0 and level <= 1);

delete from learning.mastery_state;

alter table learning.mastery_state
  drop column if exists content_block_id;

create index if not exists idx_learning_mastery_competency
  on learning.mastery_state(competency_id, person_id);

with primary_map as (
  select
    mapping.content_block_id,
    mapping.competency_id
  from catalog.content_block_competency as mapping
  where mapping.is_primary
),
totals as (
  select
    primary_map.competency_id,
    count(*)::numeric as total_blocks
  from primary_map
  group by primary_map.competency_id
),
completed as (
  select
    attempt.person_id,
    primary_map.competency_id,
    count(distinct attempt.content_block_id)::numeric as completed_blocks
  from learning.attempt as attempt
  join primary_map
    on primary_map.content_block_id = attempt.content_block_id
  where attempt.status = 'completed'
  group by attempt.person_id, primary_map.competency_id
),
latest_schedule as (
  select distinct on (legacy.person_id, primary_map.competency_id)
    legacy.person_id,
    primary_map.competency_id,
    legacy.content_block_id as source_content_block_id,
    legacy.repetitions,
    legacy.interval_days,
    legacy.ease_factor,
    legacy.last_reviewed_at,
    legacy.next_review_at,
    legacy.created_at,
    legacy.updated_at
  from tmp_mastery_state_legacy as legacy
  join primary_map
    on primary_map.content_block_id = legacy.content_block_id
  order by
    legacy.person_id,
    primary_map.competency_id,
    legacy.last_reviewed_at desc nulls last,
    legacy.updated_at desc nulls last,
    legacy.content_block_id desc
),
person_competencies as (
  select completed.person_id, completed.competency_id
  from completed
  union
  select latest_schedule.person_id, latest_schedule.competency_id
  from latest_schedule
)
insert into learning.mastery_state (
  person_id,
  competency_id,
  level,
  repetitions,
  interval_days,
  ease_factor,
  last_reviewed_at,
  next_review_at,
  created_at,
  updated_at
)
select
  person_competencies.person_id,
  person_competencies.competency_id,
  coalesce(round(completed.completed_blocks / nullif(totals.total_blocks, 0), 2), 0.00),
  coalesce(
    latest_schedule.repetitions,
    case
      when coalesce(completed.completed_blocks, 0) > 0 then 1
      else 0
    end
  ),
  coalesce(
    latest_schedule.interval_days,
    case
      when coalesce(completed.completed_blocks, 0) > 0 then 3
      else 0
    end
  ),
  coalesce(latest_schedule.ease_factor, 2.50),
  latest_schedule.last_reviewed_at,
  latest_schedule.next_review_at,
  coalesce(latest_schedule.created_at, now()),
  now()
from person_competencies
left join totals
  on totals.competency_id = person_competencies.competency_id
left join completed
  on completed.person_id = person_competencies.person_id
 and completed.competency_id = person_competencies.competency_id
left join latest_schedule
  on latest_schedule.person_id = person_competencies.person_id
 and latest_schedule.competency_id = person_competencies.competency_id;

alter table learning.mastery_state
  alter column competency_id set not null;

alter table learning.mastery_state
  add primary key (person_id, competency_id);

with latest_sources as (
  select distinct on (legacy.person_id, primary_map.competency_id)
    legacy.person_id,
    primary_map.competency_id,
    legacy.content_block_id as source_content_block_id
  from tmp_mastery_state_legacy as legacy
  join catalog.content_block_competency as primary_map
    on primary_map.content_block_id = legacy.content_block_id
   and primary_map.is_primary
  order by
    legacy.person_id,
    primary_map.competency_id,
    legacy.last_reviewed_at desc nulls last,
    legacy.updated_at desc nulls last,
    legacy.content_block_id desc
)
insert into learning.spaced_schedule (
  person_id,
  competency_id,
  source_content_block_id,
  next_review_at,
  stability,
  difficulty,
  last_reviewed_at,
  created_at,
  updated_at
)
select
  mastery.person_id,
  mastery.competency_id,
  latest_sources.source_content_block_id,
  coalesce(mastery.next_review_at, coalesce(mastery.last_reviewed_at, now()) + interval '3 days'),
  greatest(mastery.interval_days::numeric, 1),
  greatest(round(5 - mastery.ease_factor, 2), 0::numeric),
  mastery.last_reviewed_at,
  mastery.created_at,
  now()
from learning.mastery_state as mastery
left join latest_sources
  on latest_sources.person_id = mastery.person_id
 and latest_sources.competency_id = mastery.competency_id
on conflict (person_id, competency_id) do update
  set source_content_block_id = excluded.source_content_block_id,
      next_review_at = excluded.next_review_at,
      stability = excluded.stability,
      difficulty = excluded.difficulty,
      last_reviewed_at = excluded.last_reviewed_at,
      updated_at = now();

create or replace function private.sync_learning_attempt_from_legacy_progress()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_content_block_id bigint;
  v_course_id bigint;
  v_competency_id bigint;
  v_completed_blocks integer;
  v_total_blocks integer;
  v_next_review_at timestamptz;
begin
  select
    block.id,
    block.course_id
    into v_content_block_id, v_course_id
  from catalog.content_block as block
  where block.legacy_lesson_id = new.lesson_id
  limit 1;

  if v_content_block_id is null then
    return new;
  end if;

  select
    mapping.competency_id
    into v_competency_id
  from catalog.content_block_competency as mapping
  where mapping.content_block_id = v_content_block_id
    and mapping.is_primary
  order by mapping.position
  limit 1;

  if v_competency_id is null then
    select
      course_competency.competency_id
      into v_competency_id
    from catalog.course_competency as course_competency
    where course_competency.course_id = v_course_id
    order by course_competency.position
    limit 1;
  end if;

  insert into learning.attempt (
    person_id,
    content_block_id,
    status,
    completed_at,
    xp_earned,
    legacy_progress_id,
    created_at,
    updated_at
  )
  values (
    new.user_id,
    v_content_block_id,
    'completed',
    new.completed_at,
    new.xp_earned,
    new.id,
    new.completed_at,
    now()
  )
  on conflict (person_id, content_block_id) do update
    set status = excluded.status,
        completed_at = excluded.completed_at,
        xp_earned = excluded.xp_earned,
        updated_at = now();

  if v_competency_id is null then
    perform private.ensure_pilot_enrollment(new.user_id);
    return new;
  end if;

  select
    count(*)::integer
    into v_total_blocks
  from catalog.content_block_competency as mapping
  where mapping.competency_id = v_competency_id
    and mapping.is_primary;

  select
    count(distinct attempt.content_block_id)::integer
    into v_completed_blocks
  from learning.attempt as attempt
  join catalog.content_block_competency as mapping
    on mapping.content_block_id = attempt.content_block_id
   and mapping.is_primary
  where attempt.person_id = new.user_id
    and mapping.competency_id = v_competency_id
    and attempt.status = 'completed';

  v_next_review_at := new.completed_at + interval '3 days';

  insert into learning.mastery_state (
    person_id,
    competency_id,
    level,
    repetitions,
    interval_days,
    ease_factor,
    last_reviewed_at,
    next_review_at,
    created_at,
    updated_at
  )
  values (
    new.user_id,
    v_competency_id,
    coalesce(round(v_completed_blocks::numeric / nullif(v_total_blocks, 0), 2), 0.00),
    1,
    3,
    2.50,
    new.completed_at,
    v_next_review_at,
    new.completed_at,
    now()
  )
  on conflict (person_id, competency_id) do update
    set level = greatest(learning.mastery_state.level, excluded.level),
        repetitions = greatest(learning.mastery_state.repetitions, excluded.repetitions),
        interval_days = excluded.interval_days,
        ease_factor = excluded.ease_factor,
        last_reviewed_at = excluded.last_reviewed_at,
        next_review_at = excluded.next_review_at,
        updated_at = now();

  insert into learning.spaced_schedule (
    person_id,
    competency_id,
    source_content_block_id,
    next_review_at,
    stability,
    difficulty,
    last_reviewed_at,
    created_at,
    updated_at
  )
  values (
    new.user_id,
    v_competency_id,
    v_content_block_id,
    v_next_review_at,
    3,
    2.50,
    new.completed_at,
    new.completed_at,
    now()
  )
  on conflict (person_id, competency_id) do update
    set source_content_block_id = excluded.source_content_block_id,
        next_review_at = excluded.next_review_at,
        stability = excluded.stability,
        difficulty = excluded.difficulty,
        last_reviewed_at = excluded.last_reviewed_at,
        updated_at = now();

  perform private.ensure_pilot_enrollment(new.user_id);

  return new;
end;
$$;

create trigger on_legacy_progress_changed_platform_v3
after insert or update on public.progress
for each row execute procedure private.sync_learning_attempt_from_legacy_progress();

create or replace view learning.v_student_risk as
select
  schedule.person_id,
  count(*) filter (where schedule.next_review_at is not null and schedule.next_review_at < now())::integer as overdue_reviews,
  min(schedule.next_review_at) filter (where schedule.next_review_at is not null) as next_review_at,
  case
    when count(*) filter (where schedule.next_review_at is not null and schedule.next_review_at < now()) > 0 then 'at-risk'
    else 'healthy'
  end as risk_label
from learning.spaced_schedule as schedule
group by schedule.person_id;

create or replace view public.platform_course_blocks_v
with (security_invoker = true) as
select
  course.slug as course_slug,
  course.title as course_title,
  course.summary as course_summary,
  track.title as track_title,
  course.transformation_promise,
  course.duration_label,
  course.audience_label,
  course.access_model,
  course.price_label,
  course.delivery_label,
  coalesce(run.title, 'Sin cohorte abierta') as run_label,
  block.id as block_id,
  block.slug as block_slug,
  block.title as block_title,
  block.summary as block_summary,
  block.objective as block_objective,
  block.kind as block_kind,
  block.position as block_order,
  block.duration_minutes,
  block.is_public as is_free,
  block.representation_variants,
  block.expression_variants,
  block.engagement_hooks,
  block.renderer_manifest,
  block.bloom_level,
  competency.slug as competency_slug,
  competency.title as competency_title,
  competency.bloom_level as competency_bloom_level
from catalog.content_block as block
join catalog.course as course
  on course.id = block.course_id
join catalog.track as track
  on track.id = course.track_id
left join lateral (
  select course_run.title
  from delivery.course_run as course_run
  where course_run.course_id = course.id
    and course_run.status in ('open', 'closed')
  order by course_run.starts_at nulls last
  limit 1
) as run on true
left join catalog.content_block_competency as mapping
  on mapping.content_block_id = block.id
 and mapping.is_primary
left join catalog.competency as competency
  on competency.id = mapping.competency_id
where track.is_published
  and course.status = 'published';

create or replace view public.platform_portal_snapshot_v
with (security_invoker = true) as
with current_enrollment as (
  select
    enrollment_row.person_id,
    enrollment_row.id as enrollment_id,
    course_run.id as course_run_id,
    course_run.title as active_run_label,
    course.id as course_id,
    course.title as course_title
  from enrollment.enrollment as enrollment_row
  join delivery.course_run as course_run
    on course_run.id = enrollment_row.course_run_id
  join catalog.course as course
    on course.id = course_run.course_id
  where enrollment_row.person_id = (select auth.uid())
    and enrollment_row.status in ('active', 'completed')
  order by enrollment_row.updated_at desc, enrollment_row.created_at desc
  limit 1
),
course_progress as (
  select
    current_enrollment.person_id,
    count(block.id)::integer as total_blocks,
    count(distinct attempt.content_block_id)::integer as completed_blocks
  from current_enrollment
  join catalog.content_block as block
    on block.course_id = current_enrollment.course_id
  left join learning.attempt as attempt
    on attempt.person_id = current_enrollment.person_id
   and attempt.content_block_id = block.id
   and attempt.status = 'completed'
  group by current_enrollment.person_id
),
review_queue as (
  select
    schedule.person_id,
    count(*) filter (where schedule.next_review_at is not null and schedule.next_review_at < now())::integer as due_reviews_count,
    min(schedule.next_review_at) filter (where schedule.next_review_at is not null) as next_review_at
  from learning.spaced_schedule as schedule
  where schedule.person_id = (select auth.uid())
  group by schedule.person_id
)
select
  person.full_name as learner_name,
  case
    when exists (
      select 1
      from enrollment.entitlement as entitlement
      where entitlement.person_id = person.id
        and entitlement.code = 'premium-membership'
        and entitlement.status = 'active'
    ) then 'Premium entitlement'
    else 'Free entitlement'
  end as membership_label,
  current_enrollment.course_title as enrolled_course_title,
  current_enrollment.active_run_label,
  coalesce(course_progress.completed_blocks, 0) as completed_blocks,
  coalesce(course_progress.total_blocks, 0) as total_blocks,
  case
    when coalesce(course_progress.total_blocks, 0) = 0 then 0
    else floor((course_progress.completed_blocks::numeric / course_progress.total_blocks::numeric) * 100)::integer
  end as progress_percent,
  review_queue.next_review_at,
  coalesce(review_queue.due_reviews_count, 0) as due_reviews_count,
  case
    when coalesce(review_queue.due_reviews_count, 0) > 0 then 'Atencion requerida'
    else 'Ritmo saludable'
  end as at_risk_label
from current_enrollment
join identity.person as person
  on person.id = current_enrollment.person_id
left join course_progress
  on course_progress.person_id = person.id
left join review_queue
  on review_queue.person_id = person.id;

create or replace view public.platform_portal_mastery_v
with (security_invoker = true) as
with current_enrollment as (
  select
    enrollment_row.person_id,
    course.id as course_id,
    course.title as course_title
  from enrollment.enrollment as enrollment_row
  join delivery.course_run as course_run
    on course_run.id = enrollment_row.course_run_id
  join catalog.course as course
    on course.id = course_run.course_id
  where enrollment_row.person_id = (select auth.uid())
    and enrollment_row.status in ('active', 'completed')
  order by enrollment_row.updated_at desc, enrollment_row.created_at desc
  limit 1
)
select
  current_enrollment.course_title,
  competency.slug as competency_slug,
  competency.title as competency_title,
  competency.bloom_level,
  course_competency.position,
  coalesce(mastery.level, 0.00) as mastery_level,
  mastery.last_reviewed_at,
  coalesce(schedule.next_review_at, mastery.next_review_at) as next_review_at,
  coalesce(mastery.repetitions, 0) as repetitions,
  coalesce(mastery.interval_days, 0) as interval_days,
  coalesce(mastery.ease_factor, 2.50) as ease_factor,
  coalesce(schedule.next_review_at, mastery.next_review_at) is not null
    and coalesce(schedule.next_review_at, mastery.next_review_at) < now() as is_due
from current_enrollment
join catalog.course_competency as course_competency
  on course_competency.course_id = current_enrollment.course_id
join catalog.competency as competency
  on competency.id = course_competency.competency_id
left join learning.mastery_state as mastery
  on mastery.person_id = current_enrollment.person_id
 and mastery.competency_id = competency.id
left join learning.spaced_schedule as schedule
  on schedule.person_id = current_enrollment.person_id
 and schedule.competency_id = competency.id
order by course_competency.position;

grant select on public.platform_course_blocks_v to anon, authenticated;
grant select on public.platform_portal_snapshot_v to authenticated;
grant select on public.platform_portal_mastery_v to authenticated;
