-- Persist the curriculum taxonomy explicitly at course level.
-- This closes the spec gap for catalog.competency and catalog.course_competency.

create table if not exists catalog.competency (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  bloom_level catalog.bloom_level not null default 'comprender',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists catalog.course_competency (
  course_id bigint not null references catalog.course(id) on delete cascade,
  competency_id bigint not null references catalog.competency(id) on delete cascade,
  position integer not null default 1,
  created_at timestamptz not null default now(),
  primary key (course_id, competency_id),
  unique (course_id, position)
);

create index if not exists idx_catalog_course_competency_course_position
  on catalog.course_competency(course_id, position);

create index if not exists idx_catalog_course_competency_competency
  on catalog.course_competency(competency_id, course_id);

drop trigger if exists tr_catalog_competency_updated_at on catalog.competency;
create trigger tr_catalog_competency_updated_at
before update on catalog.competency
for each row execute function private.touch_updated_at();

grant select on catalog.competency, catalog.course_competency to anon, authenticated;

alter table catalog.competency enable row level security;
alter table catalog.course_competency enable row level security;

drop policy if exists competency_public_select on catalog.competency;
create policy competency_public_select on catalog.competency
for select to anon, authenticated
using (true);

drop policy if exists course_competency_public_select on catalog.course_competency;
create policy course_competency_public_select on catalog.course_competency
for select to anon, authenticated
using (
  exists (
    select 1
    from catalog.course as course
    join catalog.track as track
      on track.id = course.track_id
    where course.id = catalog.course_competency.course_id
      and course.status = 'published'
      and track.is_published
  )
);

insert into catalog.competency (
  slug,
  title,
  bloom_level
)
values
  ('foco-y-autonomia-operativa', 'Foco y autonomia operativa', 'aplicar'),
  ('pensamiento-estrategico-y-sistemico', 'Pensamiento estrategico y sistemico', 'analizar'),
  ('comunicacion-estructurada-con-evidencia', 'Comunicacion estructurada con evidencia', 'evaluar'),
  ('diseno-de-soluciones-con-ia', 'Diseno de soluciones con IA', 'crear')
on conflict (slug) do update
  set title = excluded.title,
      bloom_level = excluded.bloom_level,
      updated_at = now();

with course_row as (
  select id
  from catalog.course
  where slug = 'programa-empoderamiento-power-skills'
),
manifest as (
  select *
  from (
    values
      ('foco-y-autonomia-operativa', 1),
      ('pensamiento-estrategico-y-sistemico', 2),
      ('comunicacion-estructurada-con-evidencia', 3),
      ('diseno-de-soluciones-con-ia', 4)
  ) as manifest(slug, position)
)
insert into catalog.course_competency (
  course_id,
  competency_id,
  position
)
select
  course_row.id,
  competency.id,
  manifest.position
from course_row
join manifest
  on true
join catalog.competency as competency
  on competency.slug = manifest.slug
on conflict (course_id, competency_id) do update
  set position = excluded.position;

with course_row as (
  select id
  from catalog.course
  where slug = 'programa-empoderamiento-power-skills'
)
delete from catalog.course_competency
where course_id = (select id from course_row)
  and competency_id not in (
    select competency.id
    from catalog.competency as competency
    where competency.slug in (
      'foco-y-autonomia-operativa',
      'pensamiento-estrategico-y-sistemico',
      'comunicacion-estructurada-con-evidencia',
      'diseno-de-soluciones-con-ia'
    )
  );

create or replace view public.platform_course_competencies_v
with (security_invoker = true) as
select
  course.slug as course_slug,
  course.title as course_title,
  competency.slug as competency_slug,
  competency.title as competency_title,
  competency.bloom_level,
  course_competency.position
from catalog.course_competency as course_competency
join catalog.course as course
  on course.id = course_competency.course_id
join catalog.track as track
  on track.id = course.track_id
join catalog.competency as competency
  on competency.id = course_competency.competency_id
where track.is_published
  and course.status = 'published';

grant select on public.platform_course_competencies_v to anon, authenticated;
