-- Hardening pass: access control, billing normalization, public events contract,
-- and safe profile editing.

ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS bio TEXT NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS public.notification_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind TEXT NOT NULL,
  recipient_email TEXT,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.notification_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "No direct access to notification logs" ON public.notification_logs;
CREATE POLICY "No direct access to notification logs" ON public.notification_logs
  FOR SELECT USING (false);

CREATE OR REPLACE FUNCTION public.can_access_lesson(
  p_level_id INTEGER,
  p_is_free BOOLEAN,
  p_user_id UUID DEFAULT auth.uid()
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    COALESCE(p_is_free, false)
    OR EXISTS (
      SELECT 1
      FROM public.profiles profile
      JOIN public.levels level ON level.id = p_level_id
      WHERE profile.id = p_user_id
        AND profile.membership_status = 'active'
        AND profile.current_level >= level.orden
    );
$$;

DROP POLICY IF EXISTS "Authenticated users read all lessons" ON public.lessons;
CREATE POLICY "Users read only accessible lessons" ON public.lessons
  FOR SELECT USING (
    auth.role() = 'authenticated'
    AND public.can_access_lesson(level_id, is_free, auth.uid())
  );

ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users read events" ON public.events;
CREATE POLICY "Authenticated users read events" ON public.events
  FOR SELECT USING (auth.role() = 'authenticated');

REVOKE UPDATE ON public.profiles FROM authenticated;
GRANT UPDATE (display_name, avatar_url, bio, updated_at) ON public.profiles TO authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.progress FROM authenticated;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, display_name, membership_plan, membership_status)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1), ''),
    'free',
    'inactive'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.handle_new_user_welcome()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.notification_logs (kind, recipient_email, payload)
  VALUES (
    'welcome_email_requested',
    NEW.email,
    jsonb_build_object(
      'user_id', NEW.id,
      'display_name', COALESCE(
        NEW.raw_user_meta_data->>'full_name',
        NEW.raw_user_meta_data->>'display_name',
        split_part(NEW.email, '@', 1)
      )
    )
  );

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
