-- platform v3 cohort notifications
-- Introduce notification preferences, web push subscriptions, notification templates
-- and dispatch logs to support sequenced cohort comms from the active campus-platform surface.

create table if not exists identity.person_notification_preference (
  person_id uuid not null references identity.person(id) on delete cascade,
  channel_code text not null check (channel_code in ('email', 'web')),
  is_enabled boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (person_id, channel_code)
);

create table if not exists identity.web_push_subscription (
  id bigint generated by default as identity primary key,
  person_id uuid not null references identity.person(id) on delete cascade,
  endpoint text not null unique,
  p256dh_key text not null,
  auth_key text not null,
  user_agent text,
  is_active boolean not null default true,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists delivery.notification_template (
  id bigint generated by default as identity primary key,
  course_run_id bigint not null references delivery.course_run(id) on delete cascade,
  slug text not null,
  title text not null,
  channel_code text not null check (channel_code in ('email', 'web')),
  audience_code text not null default 'active'
    check (audience_code in ('all', 'invited', 'active', 'completed')),
  trigger_code text not null default 'manual'
    check (trigger_code in ('manual', 'before_run_start', 'after_run_start', 'after_run_end')),
  offset_days integer not null default 0,
  offset_hours integer not null default 0,
  subject_template text not null default '',
  body_template text not null default '',
  cta_label text,
  cta_url text,
  status text not null default 'draft' check (status in ('draft', 'active', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (course_run_id, slug)
);

create table if not exists delivery.notification_dispatch (
  id bigint generated by default as identity primary key,
  template_id bigint not null references delivery.notification_template(id) on delete cascade,
  course_run_id bigint not null references delivery.course_run(id) on delete cascade,
  person_id uuid not null references identity.person(id) on delete cascade,
  channel_code text not null check (channel_code in ('email', 'web')),
  scheduled_for timestamptz not null,
  status text not null default 'pending' check (status in ('pending', 'sent', 'skipped', 'failed')),
  rendered_subject text,
  rendered_body text not null,
  cta_label text,
  cta_url text,
  provider_message_id text,
  error_message text,
  sent_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (template_id, person_id, channel_code, scheduled_for)
);

create index if not exists idx_identity_notification_preference_person
  on identity.person_notification_preference(person_id, channel_code);
create index if not exists idx_identity_web_push_subscription_person
  on identity.web_push_subscription(person_id, is_active, last_seen_at desc);
create index if not exists idx_delivery_notification_template_run_status
  on delivery.notification_template(course_run_id, status, trigger_code, channel_code);
create index if not exists idx_delivery_notification_dispatch_run_status
  on delivery.notification_dispatch(course_run_id, status, scheduled_for);
create index if not exists idx_delivery_notification_dispatch_person
  on delivery.notification_dispatch(person_id, channel_code, created_at desc);

grant usage, select on all sequences in schema identity to authenticated;
grant usage, select on all sequences in schema delivery to authenticated;

grant select, insert, update on identity.person_notification_preference to authenticated;
grant select, insert, update on identity.web_push_subscription to authenticated;
grant select on delivery.notification_template, delivery.notification_dispatch to authenticated;

alter table identity.person_notification_preference enable row level security;
alter table identity.web_push_subscription enable row level security;
alter table delivery.notification_template enable row level security;
alter table delivery.notification_dispatch enable row level security;

drop trigger if exists tr_identity_person_notification_preference_updated_at on identity.person_notification_preference;
create trigger tr_identity_person_notification_preference_updated_at
before update on identity.person_notification_preference
for each row execute function private.touch_updated_at();

drop trigger if exists tr_identity_web_push_subscription_updated_at on identity.web_push_subscription;
create trigger tr_identity_web_push_subscription_updated_at
before update on identity.web_push_subscription
for each row execute function private.touch_updated_at();

drop trigger if exists tr_delivery_notification_template_updated_at on delivery.notification_template;
create trigger tr_delivery_notification_template_updated_at
before update on delivery.notification_template
for each row execute function private.touch_updated_at();

drop trigger if exists tr_delivery_notification_dispatch_updated_at on delivery.notification_dispatch;
create trigger tr_delivery_notification_dispatch_updated_at
before update on delivery.notification_dispatch
for each row execute function private.touch_updated_at();

drop policy if exists notification_preference_self_all on identity.person_notification_preference;
create policy notification_preference_self_all on identity.person_notification_preference
for all to authenticated
using ((select auth.uid()) = person_id)
with check ((select auth.uid()) = person_id);

drop policy if exists web_push_subscription_self_all on identity.web_push_subscription;
create policy web_push_subscription_self_all on identity.web_push_subscription
for all to authenticated
using ((select auth.uid()) = person_id)
with check ((select auth.uid()) = person_id);

drop policy if exists notification_template_staff_select on delivery.notification_template;
create policy notification_template_staff_select on delivery.notification_template
for select to authenticated
using (
  exists (
    select 1
    from identity.person_role as role
    where role.person_id = (select auth.uid())
      and role.role_code in ('teacher', 'admin', 'owner')
  )
);

drop policy if exists notification_template_staff_write on delivery.notification_template;
create policy notification_template_staff_write on delivery.notification_template
for all to authenticated
using (
  exists (
    select 1
    from identity.person_role as role
    where role.person_id = (select auth.uid())
      and role.role_code in ('teacher', 'admin', 'owner')
  )
)
with check (
  exists (
    select 1
    from identity.person_role as role
    where role.person_id = (select auth.uid())
      and role.role_code in ('teacher', 'admin', 'owner')
  )
);

drop policy if exists notification_dispatch_self_select on delivery.notification_dispatch;
create policy notification_dispatch_self_select on delivery.notification_dispatch
for select to authenticated
using ((select auth.uid()) = person_id);

drop policy if exists notification_dispatch_staff_select on delivery.notification_dispatch;
create policy notification_dispatch_staff_select on delivery.notification_dispatch
for select to authenticated
using (
  exists (
    select 1
    from identity.person_role as role
    where role.person_id = (select auth.uid())
      and role.role_code in ('teacher', 'admin', 'owner')
  )
);

insert into identity.person_notification_preference (
  person_id,
  channel_code,
  is_enabled
)
select
  person.id,
  'email',
  exists (
    select 1
    from enrollment.enrollment as enrollment_row
    where enrollment_row.person_id = person.id
      and enrollment_row.status in ('active', 'completed')
  )
from identity.person as person
on conflict (person_id, channel_code) do nothing;

insert into identity.person_notification_preference (
  person_id,
  channel_code,
  is_enabled
)
select
  person.id,
  'web',
  false
from identity.person as person
on conflict (person_id, channel_code) do nothing;

with run_row as (
  select course_run.id
  from delivery.course_run as course_run
  where course_run.slug = 'power-skills-pilot-open'
)
insert into delivery.notification_template (
  course_run_id,
  slug,
  title,
  channel_code,
  audience_code,
  trigger_code,
  offset_days,
  offset_hours,
  subject_template,
  body_template,
  cta_label,
  cta_url,
  status
)
select
  run_row.id,
  template.slug,
  template.title,
  template.channel_code,
  template.audience_code,
  template.trigger_code,
  template.offset_days,
  template.offset_hours,
  template.subject_template,
  template.body_template,
  template.cta_label,
  template.cta_url,
  template.status
from run_row
cross join (
  values
    (
      'bienvenida-cohorte-email',
      'Bienvenida de cohorte',
      'email',
      'active',
      'manual',
      0,
      0,
      'Tu cohorte {{run_title}} ya esta activa, {{learner_name}}',
      'Hola {{learner_name}}, ya puedes entrar a {{course_title}}. Tu cohorte {{run_title}} queda lista con {{session_count}} sesiones y la siguiente cita es {{next_session_title}} el {{next_session_starts_at}}. Usa el portal para abrir tu siguiente experiencia y mantener tu ritmo saludable.',
      'Abrir portal',
      '{{portal_url}}',
      'active'
    ),
    (
      'recordatorio-inicio-secuencia-email',
      'Recordatorio de inicio de semana',
      'email',
      'active',
      'after_run_start',
      3,
      0,
      'Checkpoint de avance en {{course_title}}',
      '{{learner_name}}, esta es tu senal de ritmo para {{course_title}}. Revisa el portal, confirma tus bloques pendientes y prepara la siguiente sesion {{next_session_title}} del {{next_session_starts_at}}. Tu cohorte {{run_title}} sigue abierta para que sostengas el progreso.',
      'Retomar ahora',
      '{{portal_url}}',
      'active'
    ),
    (
      'alerta-sesion-web',
      'Alerta web de sesion',
      'web',
      'active',
      'before_run_start',
      0,
      -2,
      'Sesion en puerta: {{next_session_title}}',
      '{{learner_name}}, en dos horas inicia {{next_session_title}} de {{course_title}}. Entra al portal para revisar materiales y llegar con tu evidencia lista.',
      'Ver agenda',
      '{{portal_url}}',
      'active'
    )
) as template (
  slug,
  title,
  channel_code,
  audience_code,
  trigger_code,
  offset_days,
  offset_hours,
  subject_template,
  body_template,
  cta_label,
  cta_url,
  status
)
on conflict (course_run_id, slug) do update
  set title = excluded.title,
      channel_code = excluded.channel_code,
      audience_code = excluded.audience_code,
      trigger_code = excluded.trigger_code,
      offset_days = excluded.offset_days,
      offset_hours = excluded.offset_hours,
      subject_template = excluded.subject_template,
      body_template = excluded.body_template,
      cta_label = excluded.cta_label,
      cta_url = excluded.cta_url,
      status = excluded.status,
      updated_at = now();
