-- Persist rubric authoring and manual review for project blocks.
-- This closes the G-12 spec gap around rubric tables and teacher review.

create or replace function private.validate_rubric_criteria()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  criterion jsonb;
  total_weight numeric := 0;
begin
  if new.criteria is null
    or jsonb_typeof(new.criteria) <> 'array'
    or jsonb_array_length(new.criteria) = 0 then
    raise exception 'La rubrica requiere criteria como arreglo no vacio';
  end if;

  for criterion in
    select value
    from jsonb_array_elements(new.criteria)
  loop
    if nullif(btrim(coalesce(criterion ->> 'slug', '')), '') is null then
      raise exception 'Cada criterio requiere slug';
    end if;

    if nullif(btrim(coalesce(criterion ->> 'title', '')), '') is null then
      raise exception 'Cada criterio requiere title';
    end if;

    if not (criterion ? 'weight') then
      raise exception 'Cada criterio requiere weight';
    end if;

    total_weight := total_weight + coalesce((criterion ->> 'weight')::numeric, 0);
  end loop;

  if total_weight <= 0 then
    raise exception 'La rubrica requiere peso total positivo';
  end if;

  return new;
end;
$$;

create table if not exists catalog.rubric (
  id bigint generated by default as identity primary key,
  course_id bigint not null references catalog.course(id) on delete cascade,
  slug text not null,
  title text not null,
  summary text,
  status text not null default 'draft'
    check (status in ('draft', 'published', 'archived')),
  scale_max integer not null default 4
    check (scale_max between 2 and 10),
  criteria jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (course_id, slug)
);

create index if not exists idx_catalog_rubric_course_status
  on catalog.rubric(course_id, status, created_at desc);

drop trigger if exists tr_catalog_rubric_updated_at on catalog.rubric;
create trigger tr_catalog_rubric_updated_at
before update on catalog.rubric
for each row execute function private.touch_updated_at();

drop trigger if exists tr_catalog_rubric_validate on catalog.rubric;
create trigger tr_catalog_rubric_validate
before insert or update on catalog.rubric
for each row execute function private.validate_rubric_criteria();

grant select on catalog.rubric to anon, authenticated;

alter table catalog.rubric enable row level security;

drop policy if exists rubric_public_select on catalog.rubric;
create policy rubric_public_select on catalog.rubric
for select to anon, authenticated
using (
  status = 'published'
  and exists (
    select 1
    from catalog.course as course
    join catalog.track as track
      on track.id = course.track_id
    where course.id = rubric.course_id
      and course.status = 'published'
      and track.is_published
  )
);

create or replace function private.validate_project_submission()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  has_text boolean := nullif(btrim(coalesce(new.submission_text, '')), '') is not null;
  has_url boolean := nullif(btrim(coalesce(new.submission_url, '')), '') is not null;
begin
  new.submission_payload := coalesce(new.submission_payload, '{}'::jsonb);
  new.criterion_scores := coalesce(new.criterion_scores, '[]'::jsonb);

  if jsonb_typeof(new.submission_payload) <> 'object' then
    raise exception 'submission_payload debe ser un objeto JSON';
  end if;

  if jsonb_typeof(new.criterion_scores) <> 'array' then
    raise exception 'criterion_scores debe ser un arreglo JSON';
  end if;

  if not (has_text or has_url or new.submission_payload <> '{}'::jsonb) then
    raise exception 'La entrega requiere al menos una evidencia';
  end if;

  if new.status = 'submitted' then
    new.reviewed_at := null;
    new.reviewer_person_id := null;
    new.review_note := null;
    new.criterion_scores := '[]'::jsonb;
    new.overall_score := null;
  else
    if new.reviewer_person_id is null then
      raise exception 'Las entregas revisadas requieren reviewer_person_id';
    end if;

    if new.reviewed_at is null then
      new.reviewed_at := now();
    end if;

    if jsonb_array_length(new.criterion_scores) = 0 then
      raise exception 'Las entregas revisadas requieren criterion_scores';
    end if;

    if new.overall_score is null or new.overall_score < 0 or new.overall_score > 100 then
      raise exception 'overall_score debe estar entre 0 y 100';
    end if;
  end if;

  return new;
end;
$$;

create table if not exists learning.project_submission (
  id bigint generated by default as identity primary key,
  person_id uuid not null references identity.person(id) on delete cascade,
  content_block_id bigint not null references catalog.content_block(id) on delete cascade,
  rubric_id bigint references catalog.rubric(id) on delete set null,
  attempt_id bigint references learning.attempt(id) on delete set null,
  status text not null default 'submitted'
    check (status in ('submitted', 'reviewed', 'changes_requested')),
  submission_text text,
  submission_url text,
  submission_payload jsonb not null default '{}'::jsonb,
  learner_note text,
  criterion_scores jsonb not null default '[]'::jsonb,
  overall_score numeric(5,2),
  review_note text,
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewer_person_id uuid references identity.person(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (person_id, content_block_id)
);

create index if not exists idx_learning_project_submission_block_status
  on learning.project_submission(content_block_id, status, submitted_at desc);

create index if not exists idx_learning_project_submission_person_updated
  on learning.project_submission(person_id, updated_at desc);

drop trigger if exists tr_learning_project_submission_updated_at on learning.project_submission;
create trigger tr_learning_project_submission_updated_at
before update on learning.project_submission
for each row execute function private.touch_updated_at();

drop trigger if exists tr_learning_project_submission_validate on learning.project_submission;
create trigger tr_learning_project_submission_validate
before insert or update on learning.project_submission
for each row execute function private.validate_project_submission();

grant select, insert, update on learning.project_submission to authenticated;

alter table learning.project_submission enable row level security;

drop policy if exists project_submission_self_select on learning.project_submission;
create policy project_submission_self_select on learning.project_submission
for select to authenticated
using ((select auth.uid()) = person_id);

drop policy if exists project_submission_self_insert on learning.project_submission;
create policy project_submission_self_insert on learning.project_submission
for insert to authenticated
with check ((select auth.uid()) = person_id);

drop policy if exists project_submission_self_update on learning.project_submission;
create policy project_submission_self_update on learning.project_submission
for update to authenticated
using ((select auth.uid()) = person_id)
with check ((select auth.uid()) = person_id);

drop policy if exists project_submission_reviewer_select on learning.project_submission;
create policy project_submission_reviewer_select on learning.project_submission
for select to authenticated
using (
  exists (
    select 1
    from identity.person_role as role
    where role.person_id = (select auth.uid())
      and role.role_code in ('teacher', 'admin', 'owner')
  )
);

drop policy if exists project_submission_reviewer_update on learning.project_submission;
create policy project_submission_reviewer_update on learning.project_submission
for update to authenticated
using (
  exists (
    select 1
    from identity.person_role as role
    where role.person_id = (select auth.uid())
      and role.role_code in ('teacher', 'admin', 'owner')
  )
)
with check (
  exists (
    select 1
    from identity.person_role as role
    where role.person_id = (select auth.uid())
      and role.role_code in ('teacher', 'admin', 'owner')
  )
);

with course_row as (
  select id
  from catalog.course
  where slug = 'programa-empoderamiento-power-skills'
)
insert into catalog.rubric (
  course_id,
  slug,
  title,
  summary,
  status,
  scale_max,
  criteria
)
select
  course_row.id,
  'rubrica-proyecto-evidencia-de-impacto',
  'Rubrica de evidencia de impacto',
  'Evalua claridad del problema, aplicacion metodologica, evidencia y reflexion final.',
  'published',
  4,
  jsonb_build_array(
    jsonb_build_object(
      'slug', 'claridad-del-problema',
      'title', 'Claridad del problema',
      'description', 'Define el reto, el contexto y el resultado esperado con precision.',
      'weight', 0.25
    ),
    jsonb_build_object(
      'slug', 'aplicacion-metodologica',
      'title', 'Aplicacion metodologica',
      'description', 'Usa el lenguaje, herramientas o framework trabajados en la ruta.',
      'weight', 0.25
    ),
    jsonb_build_object(
      'slug', 'evidencia-de-ejecucion',
      'title', 'Evidencia de ejecucion',
      'description', 'Presenta resultados, pruebas o artefactos observables.',
      'weight', 0.30
    ),
    jsonb_build_object(
      'slug', 'reflexion-y-siguientes-pasos',
      'title', 'Reflexion y siguientes pasos',
      'description', 'Explica aprendizaje, tradeoffs y plan de iteracion.',
      'weight', 0.20
    )
  )
from course_row
on conflict (course_id, slug) do update
  set title = excluded.title,
      summary = excluded.summary,
      status = excluded.status,
      scale_max = excluded.scale_max,
      criteria = excluded.criteria,
      updated_at = now();

with course_row as (
  select id
  from catalog.course
  where slug = 'programa-empoderamiento-power-skills'
)
update catalog.content_block as block
set renderer_manifest = jsonb_set(
  coalesce(
    block.renderer_manifest,
    jsonb_build_object(
      'component', 'project-block',
      'props', jsonb_build_object(),
      'a11y', jsonb_build_object(
        'role', 'article',
        'aria_label', 'Bloque de proyecto',
        'keyboard_map', jsonb_build_object()
      ),
      'offline_capable', true
    )
  ),
  '{props,rubric_id}',
  to_jsonb('rubrica-proyecto-evidencia-de-impacto'::text),
  true
)
from course_row
where block.course_id = course_row.id
  and block.kind = 'project'
  and coalesce(block.renderer_manifest #>> '{props,rubric_id}', '') = '';

create or replace view public.platform_course_blocks_v
with (security_invoker = true) as
select
  course.slug as course_slug,
  course.title as course_title,
  course.summary as course_summary,
  track.title as track_title,
  course.transformation_promise,
  course.duration_label,
  course.audience_label,
  course.access_model,
  course.price_label,
  course.delivery_label,
  coalesce(run.title, 'Sin cohorte abierta') as run_label,
  block.id as block_id,
  block.slug as block_slug,
  block.title as block_title,
  block.summary as block_summary,
  block.objective as block_objective,
  block.kind as block_kind,
  block.position as block_order,
  block.duration_minutes,
  block.is_public as is_free,
  block.representation_variants,
  block.expression_variants,
  block.engagement_hooks,
  block.renderer_manifest,
  block.bloom_level,
  competency.slug as competency_slug,
  competency.title as competency_title,
  competency.bloom_level as competency_bloom_level,
  rubric.slug as rubric_slug,
  rubric.title as rubric_title,
  rubric.scale_max as rubric_scale_max,
  rubric.criteria as rubric_criteria
from catalog.content_block as block
join catalog.course as course
  on course.id = block.course_id
join catalog.track as track
  on track.id = course.track_id
left join lateral (
  select course_run.title
  from delivery.course_run as course_run
  where course_run.course_id = course.id
    and course_run.status in ('open', 'closed')
  order by course_run.starts_at nulls last
  limit 1
) as run on true
left join catalog.content_block_competency as mapping
  on mapping.content_block_id = block.id
 and mapping.is_primary
left join catalog.competency as competency
  on competency.id = mapping.competency_id
left join catalog.rubric as rubric
  on rubric.course_id = course.id
 and rubric.slug = nullif(block.renderer_manifest #>> '{props,rubric_id}', '')
 and rubric.status = 'published'
where track.is_published
  and course.status = 'published';

grant select on public.platform_course_blocks_v to anon, authenticated;
