-- Campus Platform v3 foundation
-- Introduce bounded contexts for identity, catalog, delivery, enrollment, learning, credentials
-- while preserving the legacy public schema as a compatibility surface.

create schema if not exists private;
create schema if not exists identity;
create schema if not exists catalog;
create schema if not exists delivery;
create schema if not exists enrollment;
create schema if not exists learning;
create schema if not exists credentials;

create table if not exists identity.person (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text not null default '',
  avatar_url text,
  locale text not null default 'es-CO',
  status text not null default 'active' check (status in ('active', 'inactive', 'archived')),
  source text not null default 'legacy-public-profiles',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists identity.person_role (
  person_id uuid not null references identity.person(id) on delete cascade,
  role_code text not null check (role_code in ('student', 'teacher', 'admin', 'owner')),
  source text not null default 'legacy-sync',
  created_at timestamptz not null default now(),
  primary key (person_id, role_code)
);

create table if not exists identity.person_consent (
  id bigint generated by default as identity primary key,
  person_id uuid not null references identity.person(id) on delete cascade,
  consent_code text not null,
  status text not null default 'granted' check (status in ('granted', 'revoked', 'pending')),
  recorded_at timestamptz not null default now(),
  unique (person_id, consent_code)
);

create table if not exists catalog.track (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  summary text,
  is_published boolean not null default false,
  legacy_level_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists catalog.course (
  id bigint generated by default as identity primary key,
  track_id bigint not null references catalog.track(id) on delete cascade,
  slug text not null unique,
  title text not null,
  summary text,
  transformation_promise text,
  audience_label text not null default 'General audience',
  access_model text not null default 'free-plus-premium' check (access_model in ('free', 'free-plus-premium', 'premium-only')),
  price_label text not null default 'Piloto premium',
  delivery_label text not null default 'Cohorte guiada',
  duration_label text not null default 'TBD',
  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  legacy_program_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists catalog.content_block (
  id bigint generated by default as identity primary key,
  course_id bigint not null references catalog.course(id) on delete cascade,
  slug text not null,
  title text not null,
  summary text,
  objective text,
  kind text not null default 'lesson' check (kind in ('lesson', 'workshop', 'practice', 'milestone', 'resource')),
  body_markdown text,
  position integer not null,
  duration_minutes integer not null default 15,
  is_public boolean not null default false,
  legacy_level_id integer,
  legacy_lesson_id integer unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (course_id, slug),
  unique (course_id, position)
);

create table if not exists delivery.course_run (
  id bigint generated by default as identity primary key,
  course_id bigint not null references catalog.course(id) on delete cascade,
  slug text not null unique,
  title text not null,
  status text not null default 'draft' check (status in ('draft', 'open', 'closed', 'archived')),
  modality text not null default 'cohort-guided' check (modality in ('cohort-guided', 'self-paced', 'hybrid')),
  starts_at timestamptz,
  ends_at timestamptz,
  enrollment_opens_at timestamptz,
  enrollment_closes_at timestamptz,
  legacy_source text not null default 'legacy-public-events',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists delivery.session (
  id bigint generated by default as identity primary key,
  course_run_id bigint not null references delivery.course_run(id) on delete cascade,
  title text not null,
  description text,
  starts_at timestamptz not null,
  ends_at timestamptz,
  modality text not null default 'live-online' check (modality in ('live-online', 'recorded', 'office-hours', 'hybrid')),
  location_label text not null default 'Campus',
  meeting_url text,
  legacy_event_id integer unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists enrollment.entitlement (
  id bigint generated by default as identity primary key,
  person_id uuid not null references identity.person(id) on delete cascade,
  code text not null check (code in ('free-access', 'premium-membership')),
  status text not null default 'active' check (status in ('active', 'inactive', 'cancelled', 'past_due')),
  source text not null default 'legacy-profile-sync',
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (person_id, code)
);

create table if not exists enrollment.enrollment (
  id bigint generated by default as identity primary key,
  person_id uuid not null references identity.person(id) on delete cascade,
  course_run_id bigint not null references delivery.course_run(id) on delete cascade,
  status text not null default 'active' check (status in ('invited', 'active', 'completed', 'cancelled')),
  source text not null default 'legacy-backfill',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (person_id, course_run_id)
);

create table if not exists enrollment.checkout_intent (
  id bigint generated by default as identity primary key,
  person_id uuid references identity.person(id) on delete cascade,
  course_run_id bigint references delivery.course_run(id) on delete set null,
  idempotency_key text not null unique,
  plan_code text not null check (plan_code in ('basic', 'premium', 'enterprise')),
  status text not null default 'pending' check (status in ('pending', 'created', 'completed', 'failed')),
  stripe_session_id text unique,
  stripe_customer_id text,
  checkout_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists learning.attempt (
  id bigint generated by default as identity primary key,
  person_id uuid not null references identity.person(id) on delete cascade,
  content_block_id bigint not null references catalog.content_block(id) on delete cascade,
  status text not null default 'completed' check (status in ('started', 'completed', 'reviewed')),
  score numeric(5,2),
  completed_at timestamptz not null default now(),
  xp_earned integer not null default 0,
  legacy_progress_id integer unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (person_id, content_block_id)
);

create table if not exists learning.mastery_state (
  person_id uuid not null references identity.person(id) on delete cascade,
  content_block_id bigint not null references catalog.content_block(id) on delete cascade,
  repetitions integer not null default 0,
  interval_days integer not null default 0,
  ease_factor numeric(4,2) not null default 2.50,
  last_reviewed_at timestamptz,
  next_review_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (person_id, content_block_id)
);

create table if not exists learning.xapi_statement (
  id bigint generated by default as identity primary key,
  person_id uuid references identity.person(id) on delete cascade,
  verb text not null,
  object_id text not null,
  payload jsonb not null default '{}'::jsonb,
  emitted_at timestamptz not null default now()
);

create table if not exists credentials.badge_class (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  description text,
  issuer_name text not null default 'Campus MetodologIA',
  criteria text not null,
  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists credentials.badge_assertion (
  id bigint generated by default as identity primary key,
  badge_class_id bigint not null references credentials.badge_class(id) on delete cascade,
  person_id uuid not null references identity.person(id) on delete cascade,
  enrollment_id bigint references enrollment.enrollment(id) on delete set null,
  status text not null default 'issued' check (status in ('issued', 'revoked')),
  issued_at timestamptz not null default now(),
  verification_token text not null unique default md5(random()::text || clock_timestamp()::text),
  public_note text,
  revoked_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (badge_class_id, person_id)
);

create index if not exists idx_identity_person_email on identity.person(email);
create index if not exists idx_catalog_course_track on catalog.course(track_id);
create index if not exists idx_catalog_block_course_position on catalog.content_block(course_id, position);
create index if not exists idx_delivery_run_course on delivery.course_run(course_id, status);
create index if not exists idx_delivery_session_run_starts on delivery.session(course_run_id, starts_at);
create index if not exists idx_enrollment_entitlement_person on enrollment.entitlement(person_id, code, status);
create index if not exists idx_enrollment_person_run on enrollment.enrollment(person_id, course_run_id);
create index if not exists idx_learning_attempt_person on learning.attempt(person_id, content_block_id);
create index if not exists idx_learning_mastery_person_next on learning.mastery_state(person_id, next_review_at);
create index if not exists idx_learning_xapi_person on learning.xapi_statement(person_id, emitted_at desc);
create index if not exists idx_credentials_assertion_token on credentials.badge_assertion(verification_token);

create or replace function private.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tr_identity_person_updated_at on identity.person;
create trigger tr_identity_person_updated_at before update on identity.person
for each row execute function private.touch_updated_at();

drop trigger if exists tr_catalog_track_updated_at on catalog.track;
create trigger tr_catalog_track_updated_at before update on catalog.track
for each row execute function private.touch_updated_at();

drop trigger if exists tr_catalog_course_updated_at on catalog.course;
create trigger tr_catalog_course_updated_at before update on catalog.course
for each row execute function private.touch_updated_at();

drop trigger if exists tr_catalog_block_updated_at on catalog.content_block;
create trigger tr_catalog_block_updated_at before update on catalog.content_block
for each row execute function private.touch_updated_at();

drop trigger if exists tr_delivery_run_updated_at on delivery.course_run;
create trigger tr_delivery_run_updated_at before update on delivery.course_run
for each row execute function private.touch_updated_at();

drop trigger if exists tr_delivery_session_updated_at on delivery.session;
create trigger tr_delivery_session_updated_at before update on delivery.session
for each row execute function private.touch_updated_at();

drop trigger if exists tr_enrollment_entitlement_updated_at on enrollment.entitlement;
create trigger tr_enrollment_entitlement_updated_at before update on enrollment.entitlement
for each row execute function private.touch_updated_at();

drop trigger if exists tr_enrollment_enrollment_updated_at on enrollment.enrollment;
create trigger tr_enrollment_enrollment_updated_at before update on enrollment.enrollment
for each row execute function private.touch_updated_at();

drop trigger if exists tr_enrollment_checkout_updated_at on enrollment.checkout_intent;
create trigger tr_enrollment_checkout_updated_at before update on enrollment.checkout_intent
for each row execute function private.touch_updated_at();

drop trigger if exists tr_learning_attempt_updated_at on learning.attempt;
create trigger tr_learning_attempt_updated_at before update on learning.attempt
for each row execute function private.touch_updated_at();

drop trigger if exists tr_learning_mastery_updated_at on learning.mastery_state;
create trigger tr_learning_mastery_updated_at before update on learning.mastery_state
for each row execute function private.touch_updated_at();

drop trigger if exists tr_credentials_badge_class_updated_at on credentials.badge_class;
create trigger tr_credentials_badge_class_updated_at before update on credentials.badge_class
for each row execute function private.touch_updated_at();

drop trigger if exists tr_credentials_badge_assertion_updated_at on credentials.badge_assertion;
create trigger tr_credentials_badge_assertion_updated_at before update on credentials.badge_assertion
for each row execute function private.touch_updated_at();

grant usage on schema identity, catalog, delivery, enrollment, learning, credentials to authenticated;
grant usage on schema identity, catalog, delivery, credentials to anon;

grant usage, select on all sequences in schema identity to authenticated;
grant usage, select on all sequences in schema enrollment to authenticated;
grant usage, select on all sequences in schema learning to authenticated;
grant usage, select on all sequences in schema credentials to authenticated;

grant select, update on identity.person to authenticated;
grant select on identity.person to anon;
grant select on identity.person_role to authenticated;
grant select, insert, update on identity.person_consent to authenticated;

grant select on catalog.track, catalog.course, catalog.content_block to anon, authenticated;
grant select on delivery.course_run, delivery.session to anon, authenticated;

grant select on enrollment.entitlement, enrollment.enrollment, enrollment.checkout_intent to authenticated;
grant insert, update on enrollment.checkout_intent to authenticated;

grant select, insert, update on learning.attempt, learning.mastery_state, learning.xapi_statement to authenticated;

grant select on credentials.badge_class, credentials.badge_assertion to anon, authenticated;

alter table identity.person enable row level security;
alter table identity.person_role enable row level security;
alter table identity.person_consent enable row level security;
alter table catalog.track enable row level security;
alter table catalog.course enable row level security;
alter table catalog.content_block enable row level security;
alter table delivery.course_run enable row level security;
alter table delivery.session enable row level security;
alter table enrollment.entitlement enable row level security;
alter table enrollment.enrollment enable row level security;
alter table enrollment.checkout_intent enable row level security;
alter table learning.attempt enable row level security;
alter table learning.mastery_state enable row level security;
alter table learning.xapi_statement enable row level security;
alter table credentials.badge_class enable row level security;
alter table credentials.badge_assertion enable row level security;

drop policy if exists person_self_select on identity.person;
create policy person_self_select on identity.person
for select to authenticated
using ((select auth.uid()) = id);

drop policy if exists person_self_update on identity.person;
create policy person_self_update on identity.person
for update to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

drop policy if exists person_public_badge_lookup on identity.person;
create policy person_public_badge_lookup on identity.person
for select to anon
using (
  exists (
    select 1
    from credentials.badge_assertion as assertion
    where assertion.person_id = identity.person.id
      and assertion.status = 'issued'
  )
);

drop policy if exists person_role_self_select on identity.person_role;
create policy person_role_self_select on identity.person_role
for select to authenticated
using ((select auth.uid()) = person_id);

drop policy if exists person_consent_self_select on identity.person_consent;
create policy person_consent_self_select on identity.person_consent
for select to authenticated
using ((select auth.uid()) = person_id);

drop policy if exists person_consent_self_write on identity.person_consent;
create policy person_consent_self_write on identity.person_consent
for all to authenticated
using ((select auth.uid()) = person_id)
with check ((select auth.uid()) = person_id);

drop policy if exists track_public_select on catalog.track;
create policy track_public_select on catalog.track
for select to anon, authenticated
using (is_published);

drop policy if exists course_public_select on catalog.course;
create policy course_public_select on catalog.course
for select to anon, authenticated
using (status = 'published');

drop policy if exists content_block_access_select on catalog.content_block;
create policy content_block_access_select on catalog.content_block
for select to anon, authenticated
using (
  is_public
  or exists (
    select 1
    from enrollment.entitlement as entitlement
    where entitlement.person_id = (select auth.uid())
      and entitlement.code = 'premium-membership'
      and entitlement.status = 'active'
  )
  or exists (
    select 1
    from enrollment.enrollment as enr
    join delivery.course_run as run on run.id = enr.course_run_id
    where enr.person_id = (select auth.uid())
      and run.course_id = catalog.content_block.course_id
      and enr.status in ('active', 'completed')
  )
);

drop policy if exists run_public_select on delivery.course_run;
create policy run_public_select on delivery.course_run
for select to anon, authenticated
using (status in ('open', 'closed'));

drop policy if exists session_public_select on delivery.session;
create policy session_public_select on delivery.session
for select to anon, authenticated
using (
  exists (
    select 1
    from delivery.course_run as run
    where run.id = delivery.session.course_run_id
      and run.status in ('open', 'closed')
  )
);

drop policy if exists entitlement_self_select on enrollment.entitlement;
create policy entitlement_self_select on enrollment.entitlement
for select to authenticated
using ((select auth.uid()) = person_id);

drop policy if exists enrollment_self_select on enrollment.enrollment;
create policy enrollment_self_select on enrollment.enrollment
for select to authenticated
using ((select auth.uid()) = person_id);

drop policy if exists checkout_intent_self_all on enrollment.checkout_intent;
create policy checkout_intent_self_all on enrollment.checkout_intent
for all to authenticated
using ((select auth.uid()) = person_id)
with check ((select auth.uid()) = person_id);

drop policy if exists attempt_self_all on learning.attempt;
create policy attempt_self_all on learning.attempt
for all to authenticated
using ((select auth.uid()) = person_id)
with check ((select auth.uid()) = person_id);

drop policy if exists mastery_self_all on learning.mastery_state;
create policy mastery_self_all on learning.mastery_state
for all to authenticated
using ((select auth.uid()) = person_id)
with check ((select auth.uid()) = person_id);

drop policy if exists xapi_self_all on learning.xapi_statement;
create policy xapi_self_all on learning.xapi_statement
for all to authenticated
using ((select auth.uid()) = person_id)
with check ((select auth.uid()) = person_id);

drop policy if exists badge_class_public_select on credentials.badge_class;
create policy badge_class_public_select on credentials.badge_class
for select to anon, authenticated
using (status = 'published');

drop policy if exists badge_assertion_public_or_self_select on credentials.badge_assertion;
create policy badge_assertion_public_or_self_select on credentials.badge_assertion
for select to anon, authenticated
using (status = 'issued' or (select auth.uid()) = person_id);

create or replace function private.ensure_pilot_enrollment(p_person_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_run_id bigint;
begin
  select course_run.id
    into v_run_id
  from delivery.course_run as course_run
  where course_run.slug = 'power-skills-pilot-open'
  limit 1;

  if v_run_id is null then
    return;
  end if;

  insert into enrollment.enrollment (person_id, course_run_id, status, source)
  values (p_person_id, v_run_id, 'active', 'legacy-profile-sync')
  on conflict (person_id, course_run_id) do update
    set status = excluded.status,
        source = excluded.source,
        updated_at = now();
end;
$$;

create or replace function private.upsert_default_entitlements(
  p_person_id uuid,
  p_membership_status text,
  p_membership_plan text,
  p_membership_expires_at timestamptz
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into enrollment.entitlement (
    person_id,
    code,
    status,
    source,
    starts_at,
    metadata
  )
  values (
    p_person_id,
    'free-access',
    'active',
    'legacy-profile-sync',
    now(),
    jsonb_build_object('plan', coalesce(p_membership_plan, 'free'))
  )
  on conflict (person_id, code) do update
    set status = 'active',
        metadata = excluded.metadata,
        updated_at = now();

  if coalesce(p_membership_plan, 'free') <> 'free'
     or coalesce(p_membership_status, 'inactive') <> 'inactive' then
    insert into enrollment.entitlement (
      person_id,
      code,
      status,
      source,
      starts_at,
      ends_at,
      metadata
    )
    values (
      p_person_id,
      'premium-membership',
      case
        when coalesce(p_membership_status, 'inactive') = 'active' then 'active'
        when coalesce(p_membership_status, 'inactive') = 'past_due' then 'past_due'
        when coalesce(p_membership_status, 'inactive') = 'cancelled' then 'cancelled'
        else 'inactive'
      end,
      'legacy-profile-sync',
      now(),
      p_membership_expires_at,
      jsonb_build_object('plan', coalesce(p_membership_plan, 'premium'))
    )
    on conflict (person_id, code) do update
      set status = excluded.status,
          ends_at = excluded.ends_at,
          metadata = excluded.metadata,
          updated_at = now();
  else
    delete from enrollment.entitlement
    where person_id = p_person_id
      and code = 'premium-membership';
  end if;

  if exists (
    select 1
    from public.progress
    where user_id = p_person_id
  ) or coalesce(p_membership_status, 'inactive') = 'active' then
    perform private.ensure_pilot_enrollment(p_person_id);
  end if;
end;
$$;

create or replace function private.sync_identity_person_from_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into identity.person (
    id,
    email,
    full_name,
    source,
    created_at,
    updated_at
  )
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(coalesce(new.email, ''), '@', 1), ''),
    'auth-user-trigger',
    now(),
    now()
  )
  on conflict (id) do update
    set email = excluded.email,
        full_name = case
          when excluded.full_name = '' then identity.person.full_name
          else excluded.full_name
        end,
        updated_at = now();

  insert into identity.person_role (person_id, role_code, source)
  values (new.id, 'student', 'auth-user-trigger')
  on conflict (person_id, role_code) do nothing;

  perform private.upsert_default_entitlements(new.id, 'inactive', 'free', null);

  return new;
end;
$$;

create or replace function private.sync_identity_person_from_legacy_profile()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_email text;
begin
  select users.email
    into v_email
  from auth.users as users
  where users.id = new.id;

  insert into identity.person (
    id,
    email,
    full_name,
    avatar_url,
    source,
    created_at,
    updated_at
  )
  values (
    new.id,
    v_email,
    coalesce(nullif(new.display_name, ''), split_part(coalesce(v_email, ''), '@', 1), ''),
    new.avatar_url,
    'legacy-profile-trigger',
    coalesce(new.created_at, now()),
    now()
  )
  on conflict (id) do update
    set email = coalesce(excluded.email, identity.person.email),
        full_name = coalesce(nullif(excluded.full_name, ''), identity.person.full_name),
        avatar_url = excluded.avatar_url,
        updated_at = now();

  insert into identity.person_role (person_id, role_code, source)
  values (new.id, 'student', 'legacy-profile-trigger')
  on conflict (person_id, role_code) do nothing;

  perform private.upsert_default_entitlements(
    new.id,
    new.membership_status,
    new.membership_plan,
    new.membership_expires_at
  );

  return new;
end;
$$;

create or replace function private.sync_learning_attempt_from_legacy_progress()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_content_block_id bigint;
begin
  select block.id
    into v_content_block_id
  from catalog.content_block as block
  where block.legacy_lesson_id = new.lesson_id
  limit 1;

  if v_content_block_id is null then
    return new;
  end if;

  insert into learning.attempt (
    person_id,
    content_block_id,
    status,
    completed_at,
    xp_earned,
    legacy_progress_id,
    created_at,
    updated_at
  )
  values (
    new.user_id,
    v_content_block_id,
    'completed',
    new.completed_at,
    new.xp_earned,
    new.id,
    new.completed_at,
    now()
  )
  on conflict (person_id, content_block_id) do update
    set status = excluded.status,
        completed_at = excluded.completed_at,
        xp_earned = excluded.xp_earned,
        updated_at = now();

  insert into learning.mastery_state (
    person_id,
    content_block_id,
    repetitions,
    interval_days,
    ease_factor,
    last_reviewed_at,
    next_review_at
  )
  values (
    new.user_id,
    v_content_block_id,
    1,
    3,
    2.50,
    new.completed_at,
    new.completed_at + interval '3 days'
  )
  on conflict (person_id, content_block_id) do update
    set repetitions = greatest(learning.mastery_state.repetitions, 1),
        interval_days = excluded.interval_days,
        ease_factor = excluded.ease_factor,
        last_reviewed_at = excluded.last_reviewed_at,
        next_review_at = excluded.next_review_at,
        updated_at = now();

  perform private.ensure_pilot_enrollment(new.user_id);

  return new;
end;
$$;

insert into catalog.track (
  slug,
  title,
  summary,
  is_published,
  legacy_level_count
)
select
  'power-skills',
  'Power Skills',
  'Track piloto para replatformizacion del Campus hacia M1-M3.',
  true,
  coalesce((select count(*) from public.levels), 0)
where not exists (
  select 1 from catalog.track where slug = 'power-skills'
);

insert into catalog.course (
  track_id,
  slug,
  title,
  summary,
  transformation_promise,
  audience_label,
  access_model,
  price_label,
  delivery_label,
  duration_label,
  status,
  legacy_program_code
)
select
  track.id,
  'programa-empoderamiento-power-skills',
  'Programa de Empoderamiento en Power Skills',
  'Ruta piloto B2C para pasar de friccion operativa a ejecucion aumentada con metodo y trabajo agentico.',
  'Pasar de ocupacion reactiva a un sistema personal de ejecucion con evidencia, calendario y ceremonias.',
  'Profesionales y equipos que necesitan pasar de teoria a ritmo operativo.',
  'free-plus-premium',
  'Piloto premium desde USD 29',
  'Cohorte guiada + replay',
  '4 bloques, 3 sesiones en vivo, 1 badge final',
  'published',
  'programa-empoderamiento-power-skills'
from catalog.track as track
where track.slug = 'power-skills'
  and not exists (
    select 1 from catalog.course where slug = 'programa-empoderamiento-power-skills'
  );

insert into delivery.course_run (
  course_id,
  slug,
  title,
  status,
  modality,
  starts_at,
  ends_at,
  enrollment_opens_at,
  enrollment_closes_at,
  legacy_source
)
select
  course.id,
  'power-skills-pilot-open',
  'Cohorte mayo 2026 abierta',
  'open',
  'cohort-guided',
  now(),
  now() + interval '30 days',
  now(),
  now() + interval '15 days',
  'platform-v3-foundation'
from catalog.course as course
where course.slug = 'programa-empoderamiento-power-skills'
  and not exists (
    select 1 from delivery.course_run where slug = 'power-skills-pilot-open'
  );

insert into credentials.badge_class (
  slug,
  title,
  description,
  issuer_name,
  criteria,
  status
)
select
  'badge-power-skills-pilot',
  'Power Skills Pilot Badge',
  'Credencial verificable para cohortes del programa piloto de empoderamiento.',
  'Campus MetodologIA',
  'Completar la ruta piloto y participar en la clinic final con una mejora operativa verificable.',
  'published'
where not exists (
  select 1 from credentials.badge_class where slug = 'badge-power-skills-pilot'
);

insert into identity.person (
  id,
  email,
  full_name,
  source,
  created_at,
  updated_at
)
select
  users.id,
  users.email,
  coalesce(users.raw_user_meta_data ->> 'display_name', split_part(coalesce(users.email, ''), '@', 1), ''),
  'auth-user-backfill',
  now(),
  now()
from auth.users as users
on conflict (id) do update
  set email = excluded.email,
      full_name = case
        when excluded.full_name = '' then identity.person.full_name
        else excluded.full_name
      end,
      updated_at = now();

insert into identity.person (
  id,
  email,
  full_name,
  avatar_url,
  source,
  created_at,
  updated_at
)
select
  profile.id,
  users.email,
  coalesce(nullif(profile.display_name, ''), split_part(coalesce(users.email, ''), '@', 1), 'participante-campus'),
  profile.avatar_url,
  'legacy-profile-backfill',
  profile.created_at,
  now()
from public.profiles as profile
left join auth.users as users
  on users.id = profile.id
on conflict (id) do update
  set email = coalesce(excluded.email, identity.person.email),
      full_name = coalesce(nullif(excluded.full_name, ''), identity.person.full_name),
      avatar_url = excluded.avatar_url,
      updated_at = now();

insert into identity.person_role (person_id, role_code, source)
select identity_person.id, 'student', 'foundation-backfill'
from identity.person as identity_person
on conflict (person_id, role_code) do nothing;

with ordered_lessons as (
  select
    lesson.id as legacy_lesson_id,
    lesson.level_id as legacy_level_id,
    lesson.titulo,
    coalesce(level.titulo, 'Modulo legacy') as level_title,
    coalesce(level.descripcion, 'Bloque migrado desde campus-v2.') as level_summary,
    lesson.contenido_markdown,
    lesson.tipo,
    lesson.orden,
    lesson.duracion_minutos,
    lesson.is_free,
    row_number() over (order by level.orden, lesson.orden, lesson.id) as platform_order
  from public.lessons as lesson
  join public.levels as level
    on level.id = lesson.level_id
),
course_row as (
  select course.id
  from catalog.course as course
  where course.slug = 'programa-empoderamiento-power-skills'
)
insert into catalog.content_block (
  course_id,
  slug,
  title,
  summary,
  objective,
  kind,
  body_markdown,
  position,
  duration_minutes,
  is_public,
  legacy_level_id,
  legacy_lesson_id
)
select
  course_row.id,
  'legacy-' || ordered_lessons.legacy_lesson_id::text,
  ordered_lessons.titulo,
  ordered_lessons.level_summary,
  ordered_lessons.level_title,
  case ordered_lessons.tipo
    when 'mixed' then 'practice'
    when 'pdf' then 'resource'
    else 'lesson'
  end,
  ordered_lessons.contenido_markdown,
  ordered_lessons.platform_order,
  coalesce(ordered_lessons.duracion_minutos, 15),
  ordered_lessons.is_free,
  ordered_lessons.legacy_level_id,
  ordered_lessons.legacy_lesson_id
from ordered_lessons
cross join course_row
on conflict (legacy_lesson_id) do update
  set title = excluded.title,
      summary = excluded.summary,
      objective = excluded.objective,
      kind = excluded.kind,
      body_markdown = excluded.body_markdown,
      position = excluded.position,
      duration_minutes = excluded.duration_minutes,
      is_public = excluded.is_public,
      updated_at = now();

with run_row as (
  select course_run.id
  from delivery.course_run as course_run
  where course_run.slug = 'power-skills-pilot-open'
)
insert into delivery.session (
  course_run_id,
  title,
  description,
  starts_at,
  ends_at,
  modality,
  location_label,
  meeting_url,
  legacy_event_id
)
select
  run_row.id,
  event.titulo,
  event.descripcion,
  event.fecha_inicio,
  event.fecha_fin,
  case event.tipo
    when 'office_hours' then 'office-hours'
    when 'webinar' then 'hybrid'
    else 'live-online'
  end,
  case
    when nullif(event.url_meeting, '') is null then 'Campus live'
    else 'Meet + replay'
  end,
  nullif(event.url_meeting, ''),
  event.id
from public.events as event
cross join run_row
on conflict (legacy_event_id) do update
  set title = excluded.title,
      description = excluded.description,
      starts_at = excluded.starts_at,
      ends_at = excluded.ends_at,
      modality = excluded.modality,
      location_label = excluded.location_label,
      meeting_url = excluded.meeting_url,
      updated_at = now();

select private.upsert_default_entitlements(
  profile.id,
  profile.membership_status,
  profile.membership_plan,
  profile.membership_expires_at
)
from public.profiles as profile;

with run_row as (
  select course_run.id
  from delivery.course_run as course_run
  where course_run.slug = 'power-skills-pilot-open'
)
insert into enrollment.enrollment (
  person_id,
  course_run_id,
  status,
  source
)
select
  profile.id,
  run_row.id,
  case
    when exists (
      select 1 from public.progress as progress where progress.user_id = profile.id
    ) then 'active'
    when profile.membership_status = 'active' then 'active'
    else 'invited'
  end,
  'legacy-backfill'
from public.profiles as profile
cross join run_row
where exists (
    select 1 from public.progress as progress where progress.user_id = profile.id
  )
  or profile.membership_status <> 'inactive'
on conflict (person_id, course_run_id) do update
  set status = excluded.status,
      source = excluded.source,
      updated_at = now();

insert into learning.attempt (
  person_id,
  content_block_id,
  status,
  completed_at,
  xp_earned,
  legacy_progress_id,
  created_at,
  updated_at
)
select
  progress.user_id,
  block.id,
  'completed',
  progress.completed_at,
  progress.xp_earned,
  progress.id,
  progress.completed_at,
  now()
from public.progress as progress
join catalog.content_block as block
  on block.legacy_lesson_id = progress.lesson_id
on conflict (person_id, content_block_id) do update
  set status = excluded.status,
      completed_at = excluded.completed_at,
      xp_earned = excluded.xp_earned,
      updated_at = now();

insert into learning.mastery_state (
  person_id,
  content_block_id,
  repetitions,
  interval_days,
  ease_factor,
  last_reviewed_at,
  next_review_at
)
select
  attempt.person_id,
  attempt.content_block_id,
  1,
  3,
  2.50,
  attempt.completed_at,
  attempt.completed_at + interval '3 days'
from learning.attempt as attempt
on conflict (person_id, content_block_id) do update
  set repetitions = greatest(learning.mastery_state.repetitions, excluded.repetitions),
      interval_days = excluded.interval_days,
      ease_factor = excluded.ease_factor,
      last_reviewed_at = excluded.last_reviewed_at,
      next_review_at = excluded.next_review_at,
      updated_at = now();

with badge_class_row as (
  select badge_class.id
  from credentials.badge_class as badge_class
  where badge_class.slug = 'badge-power-skills-pilot'
),
course_row as (
  select course.id
  from catalog.course as course
  where course.slug = 'programa-empoderamiento-power-skills'
),
completion_target as (
  select count(*)::integer as total_blocks
  from catalog.content_block as block
  where block.course_id = (select id from course_row)
),
eligible as (
  select
    enrollment_row.id as enrollment_id,
    enrollment_row.person_id
  from enrollment.enrollment as enrollment_row
  join delivery.course_run as course_run
    on course_run.id = enrollment_row.course_run_id
  join course_row
    on course_row.id = course_run.course_id
  cross join completion_target
  where (
    select count(*)
    from learning.attempt as attempt
    join catalog.content_block as block
      on block.id = attempt.content_block_id
    where attempt.person_id = enrollment_row.person_id
      and block.course_id = course_row.id
      and attempt.status = 'completed'
  ) >= completion_target.total_blocks
)
insert into credentials.badge_assertion (
  badge_class_id,
  person_id,
  enrollment_id,
  status,
  public_note
)
select
  badge_class_row.id,
  eligible.person_id,
  eligible.enrollment_id,
  'issued',
  'Migrada desde el piloto legacy.'
from eligible
cross join badge_class_row
on conflict (badge_class_id, person_id) do nothing;

drop trigger if exists on_auth_user_created_platform_v3 on auth.users;
create trigger on_auth_user_created_platform_v3
after insert on auth.users
for each row execute procedure private.sync_identity_person_from_auth_user();

drop trigger if exists on_legacy_profile_changed_platform_v3 on public.profiles;
create trigger on_legacy_profile_changed_platform_v3
after insert or update on public.profiles
for each row execute procedure private.sync_identity_person_from_legacy_profile();

drop trigger if exists on_legacy_progress_changed_platform_v3 on public.progress;
create trigger on_legacy_progress_changed_platform_v3
after insert or update on public.progress
for each row execute procedure private.sync_learning_attempt_from_legacy_progress();

create or replace view learning.v_student_risk as
select
  mastery.person_id,
  count(*) filter (where mastery.next_review_at is not null and mastery.next_review_at < now())::integer as overdue_reviews,
  min(mastery.next_review_at) filter (where mastery.next_review_at is not null) as next_review_at,
  case
    when count(*) filter (where mastery.next_review_at is not null and mastery.next_review_at < now()) > 0 then 'at-risk'
    else 'healthy'
  end as risk_label
from learning.mastery_state as mastery
group by mastery.person_id;

create or replace view public.platform_course_catalog_v
with (security_invoker = true) as
select
  course.slug as course_slug,
  course.title as course_title,
  course.summary as course_summary,
  track.title as track_title,
  course.audience_label,
  course.access_model,
  course.price_label,
  course.delivery_label,
  coalesce(run.title, 'Sin cohorte abierta') as run_label,
  null::integer as progress_percent
from catalog.course as course
join catalog.track as track
  on track.id = course.track_id
left join lateral (
  select course_run.title
  from delivery.course_run as course_run
  where course_run.course_id = course.id
    and course_run.status in ('open', 'closed')
  order by course_run.starts_at nulls last
  limit 1
) as run on true
where track.is_published
  and course.status = 'published';

create or replace view public.platform_course_blocks_v
with (security_invoker = true) as
select
  course.slug as course_slug,
  course.title as course_title,
  course.summary as course_summary,
  track.title as track_title,
  course.transformation_promise,
  course.duration_label,
  course.audience_label,
  course.access_model,
  course.price_label,
  course.delivery_label,
  coalesce(run.title, 'Sin cohorte abierta') as run_label,
  block.id as block_id,
  block.slug as block_slug,
  block.title as block_title,
  block.summary as block_summary,
  block.objective as block_objective,
  block.kind as block_kind,
  block.position as block_order,
  block.duration_minutes,
  block.is_public as is_free
from catalog.content_block as block
join catalog.course as course
  on course.id = block.course_id
join catalog.track as track
  on track.id = course.track_id
left join lateral (
  select course_run.title
  from delivery.course_run as course_run
  where course_run.course_id = course.id
    and course_run.status in ('open', 'closed')
  order by course_run.starts_at nulls last
  limit 1
) as run on true
where track.is_published
  and course.status = 'published';

create or replace view public.platform_open_runs_v
with (security_invoker = true) as
select
  course.slug as course_slug,
  course_run.title as run_label,
  session.id as session_id,
  session.title as session_title,
  session.starts_at,
  session.ends_at,
  session.modality,
  session.location_label
from delivery.session as session
join delivery.course_run as course_run
  on course_run.id = session.course_run_id
join catalog.course as course
  on course.id = course_run.course_id
where course_run.status in ('open', 'closed');

create or replace view public.platform_portal_snapshot_v
with (security_invoker = true) as
with current_enrollment as (
  select
    enrollment_row.person_id,
    enrollment_row.id as enrollment_id,
    course_run.id as course_run_id,
    course_run.title as active_run_label,
    course.id as course_id,
    course.title as course_title
  from enrollment.enrollment as enrollment_row
  join delivery.course_run as course_run
    on course_run.id = enrollment_row.course_run_id
  join catalog.course as course
    on course.id = course_run.course_id
  where enrollment_row.person_id = (select auth.uid())
    and enrollment_row.status in ('active', 'completed')
  order by enrollment_row.updated_at desc, enrollment_row.created_at desc
  limit 1
)
select
  person.full_name as learner_name,
  case
    when exists (
      select 1
      from enrollment.entitlement as entitlement
      where entitlement.person_id = person.id
        and entitlement.code = 'premium-membership'
        and entitlement.status = 'active'
    ) then 'Premium entitlement'
    else 'Free entitlement'
  end as membership_label,
  current_enrollment.course_title as enrolled_course_title,
  current_enrollment.active_run_label,
  count(attempt.id)::integer as completed_blocks,
  count(block.id)::integer as total_blocks,
  case
    when count(block.id) = 0 then 0
    else floor((count(attempt.id)::numeric / count(block.id)::numeric) * 100)::integer
  end as progress_percent,
  min(mastery.next_review_at) filter (where mastery.next_review_at is not null) as next_review_at,
  case
    when count(*) filter (where mastery.next_review_at is not null and mastery.next_review_at < now()) > 0 then 'Atencion requerida'
    else 'Ritmo saludable'
  end as at_risk_label
from current_enrollment
join identity.person as person
  on person.id = current_enrollment.person_id
join catalog.content_block as block
  on block.course_id = current_enrollment.course_id
left join learning.attempt as attempt
  on attempt.person_id = person.id
 and attempt.content_block_id = block.id
 and attempt.status = 'completed'
left join learning.mastery_state as mastery
  on mastery.person_id = person.id
 and mastery.content_block_id = block.id
group by
  person.id,
  person.full_name,
  current_enrollment.course_title,
  current_enrollment.active_run_label;

create or replace view public.platform_badge_assertions_v
with (security_invoker = true) as
select
  assertion.verification_token as token,
  person.full_name as learner_name,
  coalesce(course.title, badge_class.title) as course_title,
  assertion.issued_at,
  badge_class.issuer_name as issuer,
  assertion.status,
  badge_class.criteria
from credentials.badge_assertion as assertion
join credentials.badge_class as badge_class
  on badge_class.id = assertion.badge_class_id
join identity.person as person
  on person.id = assertion.person_id
left join enrollment.enrollment as enrollment_row
  on enrollment_row.id = assertion.enrollment_id
left join delivery.course_run as course_run
  on course_run.id = enrollment_row.course_run_id
left join catalog.course as course
  on course.id = course_run.course_id
where assertion.status = 'issued'
  and badge_class.status = 'published';

grant select on public.platform_course_catalog_v to anon, authenticated;
grant select on public.platform_course_blocks_v to anon, authenticated;
grant select on public.platform_open_runs_v to anon, authenticated;
grant select on public.platform_portal_snapshot_v to authenticated;
grant select on public.platform_badge_assertions_v to anon, authenticated;
