create schema if not exists audit;

create table if not exists identity.dsar_request (
  id uuid primary key default gen_random_uuid(),
  person_id uuid not null,
  kind text not null
    check (kind in ('access', 'deletion', 'access_deletion', 'rectification', 'portability')),
  status text not null default 'processing'
    check (status in ('processing', 'exported', 'deleted', 'failed')),
  request_source text not null default 'edge-function',
  verification_method text not null default 'self_service_jwt',
  requested_at timestamptz not null default now(),
  verified_at timestamptz,
  due_at timestamptz not null default now() + interval '30 days',
  resolved_at timestamptz,
  delete_confirmed_at timestamptz,
  export_sha256 text,
  evidence jsonb not null default '{}'::jsonb,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (resolved_at is null or resolved_at >= requested_at),
  check (jsonb_typeof(evidence) = 'object')
);

create index if not exists idx_identity_dsar_request_person_requested
  on identity.dsar_request(person_id, requested_at desc);

create index if not exists idx_identity_dsar_request_status_due
  on identity.dsar_request(status, due_at)
  where status in ('processing', 'failed');

drop trigger if exists tr_identity_dsar_request_updated_at on identity.dsar_request;
create trigger tr_identity_dsar_request_updated_at
before update on identity.dsar_request
for each row execute function private.touch_updated_at();

grant select on identity.dsar_request to authenticated;
grant all on identity.dsar_request to service_role;

alter table identity.dsar_request enable row level security;

drop policy if exists dsar_request_self_select on identity.dsar_request;
create policy dsar_request_self_select on identity.dsar_request
for select to authenticated
using ((select auth.uid()) = person_id);

drop policy if exists dsar_request_staff_select on identity.dsar_request;
create policy dsar_request_staff_select on identity.dsar_request
for select to authenticated
using (
  exists (
    select 1
    from identity.person_role as role
    where role.person_id = (select auth.uid())
      and role.role_code in ('teacher', 'admin', 'owner')
  )
);

create table if not exists audit.event (
  id bigint generated by default as identity primary key,
  event_type text not null,
  severity text not null default 'info'
    check (severity in ('debug', 'info', 'warning', 'error', 'critical')),
  source text not null default 'edge-function',
  actor_person_id uuid,
  subject_person_id uuid,
  dsar_request_id uuid references identity.dsar_request(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  check (jsonb_typeof(metadata) = 'object')
);

create index if not exists idx_audit_event_type_created
  on audit.event(event_type, created_at desc);

create index if not exists idx_audit_event_subject_created
  on audit.event(subject_person_id, created_at desc);

create index if not exists idx_audit_event_dsar_request
  on audit.event(dsar_request_id, created_at desc)
  where dsar_request_id is not null;

create or replace function private.prevent_audit_event_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception 'audit.event is append-only';
end;
$$;

drop trigger if exists tr_audit_event_append_only on audit.event;
create trigger tr_audit_event_append_only
before update or delete on audit.event
for each row execute function private.prevent_audit_event_mutation();

alter table audit.event enable row level security;

drop policy if exists audit_event_service_role_all on audit.event;
create policy audit_event_service_role_all on audit.event
for all to service_role
using (true)
with check (true);

grant usage on schema audit to service_role;
grant usage, select on all sequences in schema audit to service_role;
grant all on all tables in schema audit to service_role;

alter default privileges in schema audit grant all on tables to service_role;
alter default privileges in schema audit grant usage, select on sequences to service_role;

alter role authenticator
set pgrst.db_schemas = 'public, graphql_public, identity, catalog, delivery, enrollment, learning, credentials, audit';

notify pgrst, 'reload config';
notify pgrst, 'reload schema';
